### ISSUE TITLE
the output of pcm-iio on EMR may not be correct

### ISSUE THREAD

**Issue by wangyi4** [opcm/pcm#946]
I ran pcm-iio on EMR6554s. It seems the output from pcm-iio program is not correct. QAT are connected to PCIe1 and PCIe4.

|IIO Stack 4 - PCIe1 |
    |0000:6F:01.0|Gen0 x0 |8086:0B25 Intel Corporation unknown device; Part: 0, 1, 2,  
    |0000:70:00.0|Gen1 x1 |8086:4940 Intel Corporation 4xxx Series QAT; Part: 4,  
    |0000:72:00.0|Gen0 x0 |8086:2710 Intel Corporation unknown device; Part: 5,  

 ____________________ ________ _______ _______ ________ ____________ __________ ______________ ______________ ______________ ____________ ____________ ________________ 
|IIO Stack 9  - PCIe4|
    |0000:79:01.0|Gen0 x0 |8086:0B25 Intel Corporation unknown device; Part: 0, 1, 2,  
    |0000:7A:00.0|Gen1 x1 |8086:4940 Intel Corporation 4xxx Series QAT; Part: 4,  
    |0000:7C:00.0|Gen0 x0 |8086:2710 Intel Corporation unknown device; Part: 5, 

**Comment by ogbrugge** [comment]
Are you using the latest version of pcm?

**Comment by wangyi4** [comment]
Yes, the latest version also has such issue.

**Comment by rdementi** [comment]
we have a fix which should be merged soon

**Comment by rdementi** [comment]
fixed in the master branch now

**Comment by wangyi4** [comment]
I tried the latest master. It includes the fixings mentioned above. But the issue is still there.

**Comment by rdementi** [comment]
@wangyi4 thank you for your feedback. Could you please share the current output from your system and the expected output from your point of view?

**Comment by wangyi4** [comment]
The output is the same as what I reported before. 
My understanding is that QAT should be connected to IDX instead of PCIe, like 

|IIO Stack 0 - **IDX0**  |IB write|IB read|OB read|OB write|IOTLB Lookup|IOTLB Miss|Ctxt Cache Hit|256T Cache Hit|512G Cache Hit|1G Cache Hit|2M Cache Hit|IOMMU Mem Access|
|____________________|________|_______|_______|________|____________|__________|______________|______________|______________|____________|____________|________________|
| Part0              |   0    |   0   |   0   |   0    | 360        |   0      |   0          |   0          |   0          |   0        |   0        |   0            |
| Part1              |   0    |   0   |   0   |   0    |
| Part2              |   0    |   0   |   0   |   0    |
| Part3              |   0    |   0   |   0   |   0    |
| Part4              |7680    |3840   |   0   |   0    |
| Part5              |   0    |   0   |   0   |   0    |
| Part6              |   0    |   0   |   0   |   0    |
| Part7              |   0    |   0   |   0   |   0    |
|____________________|________|_______|_______|________|____________|__________|______________|______________|______________|____________|____________|________________|
    |0000:6A:01.0|Gen0 x0 |8086:0B25 Intel Corporation unknown device; Part: 0, 1, 2
    **|0000:6B:00.0|Gen1 x1 |8086:4940 Intel Corporation 4xxx Series QAT; Part: 4**
    |0000:6D:00.0|Gen0 x0 |8086:2710 Intel Corporation unknown device; Part: 5

Correct me if my understanding is wrong.

On GNR-SP , I saw QAT was connected to HCx.

_________________________ ________ _______ _______ ________ ____________ __________ ______________ ______________ ______________ ____________ ____________ ________________
|IIO Stack 1  - HCx0      |IB write|IB read|OB read|OB write|IOTLB Lookup|IOTLB Miss|Ctxt Cache Hit|256T Cache Hit|512G Cache Hit|1G Cache Hit|2M Cache Hit|IOMMU Mem Access|
|_________________________|________|_______|_______|________|____________|__________|______________|______________|______________|____________|____________|________________|
| Part0                   |   0    |   0   |   0   |   0    |   0        |   0      |   0          |   0          |   0          |   0        |   0        |   0            |
| Part1                   |   0    |   0   |   0   |   0    |
| Part2                   |   0    |   0   |   0   |   0    |
| Part3                   |   0    |   0   |   0   |   0    |
| Part4                   |   0    |   0   |   0   |   0    |
| Part5                   |   0    |   0   |   0   |   0    |
| Part6                   |   0    |   0   |   0   |   0    |
| Part7                   |   0    |   0   |   0   |   0    |
|_________________________|________|_______|_______|________|____________|__________|______________|______________|______________|____________|____________|________________|
    |0000:00:01.0|Gen0 x0 |8086:0B25 Intel Corporation unknown device; Part: 0
    |0000:01:00.0|Gen1 x1 |8086:4944 Intel Corporation 4xxx Series QAT; Part: 4
    |0000:03:00.0|Gen0 x0 |8086:2714 Intel Corporation unknown device; Part: 5

**Comment by antonovalexnn** [comment]
Hi @wangyi4,
You are right. PCIe device mapping on stack ID for your platform is incorrect. I will contact you directly
